apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
spec:
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
      - name: billing-service
        image: billing-micro-service:1.0
        resources:
          limits:
            memory: "1G"
            cpu: "500m"
        env:
          - name : EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key:  eureka_service_adresse
        ports:
        - containerPort: 8083
 
 
---
apiVersion: v1
kind: Service
metadata:
  name: billing-service-svc
spec:
  selector:
    app: billing-service
  ports:
  - port: 8083
    targetPort: 8083

