apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway
spec:
  selector:
    matchLabels:
      app: cloud-gateway
  template:
    metadata:
      labels:
        app: cloud-gateway
    spec:
      containers:
      - name: cloud-gateway
        image: gateway-service:1.0
        resources:
          limits:
            memory: "1G"
            cpu: "500m"
        env:
          - name : EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key:  eureka_service_adresse
        ports:
        - containerPort: 9999      

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
spec:
  selector:
    app: cloud-gateway
  type: LoadBalancer
  ports:
  - port: 9999
    targetPort: 9999
    protocol: TCP

